- name: install nginx on redhat
  hosts: nginx
  #hosts: all
  become: yes
  tasks:
    - name: install nginx
      ansible.builtin.package:
        name: nginx
        state: present
    - name: start and enable nginx service
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes